server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: shopping.website.userschema
    password: user
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true
